#!/usr/bin/env bash
# Build the fylun-code binary for the current platform.
# Requires bun (upstream pins bun 1.3.x): https://bun.sh
set -euo pipefail
cd "$(dirname "$0")/.."

command -v bun >/dev/null 2>&1 || { echo "bun is required: curl -fsSL https://bun.sh/install | bash" >&2; exit 1; }

./scripts/fetch-upstream.sh
./scripts/apply-overlay.sh

# Vendor the Fylun auth plugin into the opencode source tree so it compiles
# INTO the binary (registered in internalPlugins by patch 08 — same mechanism
# opencode uses for its own Copilot/xAI/etc. providers). No npm package, no
# runtime install. Source of truth is plugin/src/index.ts.
cp plugin/src/index.ts upstream/packages/opencode/src/plugin/fylun-auth.ts

(cd upstream && bun install)

# Bake a CURATED models.dev catalog. Patch 06 makes the baked snapshot
# authoritative at runtime (no models.dev fetch), so whatever is here is the
# whole provider picker.
#
# distribution/models.json is generated by scripts/gen-catalog.mjs: Fylun (from
# distribution/models-fylun.json, itself generated from @fylun/ai's
# ModelRegistry — see README "Regenerating models") plus a curated slice of
# models.dev. Curated for usability, not to suppress anyone: all 177 upstream
# providers would be an unusable dialog and 3.3MB in the binary, and OpenCode
# Zen / Go are deliberately in the list. Providers outside it stay reachable via
# the dialog's "Other / custom provider" entry.
#
# Regenerate with: node scripts/gen-catalog.mjs
(cd upstream/packages/opencode && MODELS_DEV_API_JSON="../../../distribution/models.json" bun run script/build.ts --single)

echo
echo "binary:"
ls upstream/packages/opencode/dist/*/bin/fylun-code
